SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
WHERE NOT EXISTS(
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID = II.ITEM_ID
)
ORDER BY II.ITEM_ID DESC


