SELECT UU.USER_ID, UU.NICKNAME, CONCAT(UU.CITY, " ", UU.STREET_ADDRESS1, " ", UU.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4) , "-", SUBSTRING(TLNO, 8, 4)) AS 'TLNO'
FROM USED_GOODS_USER UU
JOIN USED_GOODS_BOARD UB
ON UU.USER_ID = UB.WRITER_ID
GROUP BY UU.USER_ID
HAVING COUNT(USER_ID) >= 3
ORDER BY UU.USER_ID DESC